version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: python main.py
  db:
    image: python:3
    volumes:
      - db-data:/data
    command: sh -c "sqlite3 /data/test.db"
volumes:
  db-data: